apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  labels:
    name: flask-app-pod
    app: flask-app
spec:
  containers:
  - name: flask-container
    image: oranmz/foodly:flask-app
    ports:
      - containerPort: 5000
