name: PostgreSQL service example
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y postgresql postgresql-contrib
          pip install django
          sudo apt install -y python3-dev libpq-dev
          pip install psycopg2
          sudo -u postgres psql -f setup.sql

      - name: Run Tests
        run: |
          python manage.py test core
