name: Temporary PostgreSQL
on:
  push:
    branches:
      - main

jobs:
  postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          timeout=120
          count=0
          until nc -z localhost 5432; do
            sleep 1
            count=$((count+1))
            if [[ $count -gt $timeout ]]; then
              echo "PostgreSQL failed to start within $timeout seconds."
              exit 1
            fi
          done
      - name: Show PostgreSQL connection details
        run: |
          echo "PostgreSQL is running on localhost:5432"
          echo "Database: testdb"
          echo "Username: testuser"
          echo "Password: testpassword"
