name: Temporary PostgreSQL
on:
  push:
    branches:
      - main

jobs:
  postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: 123123
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          timeout=120
          count=0
          until nc -z localhost 5432; do
            sleep 1
            count=$((count+1))
            if [[ $count -gt $timeout ]]; then
              echo "PostgreSQL failed to start within $timeout seconds."
              exit 1
            fi
          done

      - name: Checkout code
        uses: actions/checkout@v2
        
      # Copy the file from the repository to the workflow directory

      - name: Execute SQL file and print it 
        run: |
          psql -d testdb -f backend/db/data.sql
          psql -d testdb -c "SELECT * FROM users"
        env:
          PGHOST: localhost
          PGUSER: testuser
          PGDATABASE: testdb
          PGPASSWORD: ${{ secrets.PG_PASSWORD }}

